name: furniture_design
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.2
  eva_icons_flutter: ^3.0.0
  firebase_core: ^0.7.0
  fluttericon: ^1.0.7
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  flutter_svg: ^0.19.3
  google_sign_in: ^4.0.1
  flutter_staggered_grid_view: ^0.3.4
  scrollable_positioned_list: ^0.1.8
  image_picker: ^0.6.7
  permission_handler: ^5.0.0+1
 



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
